### ISSUE TITLE
Зависает на выполнении провежена

### ISSUE THREAD

**Issue by dapi** [BrandyMint/kiiiosk-vagrant#2]
@saymon21root Денис, я объеденил все вагрант-файлы в один, вроде все норм, нона этапе выполнения провижена вагрант подвисает (по ssh заходит, но из провижена не выходит). Ощущение что в провижене ожидается ввод с консоли или тп.

**Comment by dkhabarov** [comment]
Поправил. Было в паре мест.

**Comment by dapi** [comment]
Все равно зависает. Делаю vagrant destroy; vagrant up и он висит из up-а не выходит.

Как посмотреть лог провижена?

**Comment by dkhabarov** [comment]
Останови провижен, зайди по ssh, выполни /tmp/vagrant-shell, или при провижене, посмотри что в процессах весит.
У меня нету никаких зависаний. Он в принципе долго работает при начальном провижене. Может ты просто не дождался?

**Comment by dkhabarov** [comment]
Да, похоже всё-же было зависание. Симлинки на конфиги у тебя были не верны.

**Comment by dapi** [comment]
Ага, но все равно висит. А сколько у тебя провижен выполняется по времени?

**Comment by dkhabarov** [comment]
Запустил time vagrant up. Скажу чуть позже. Но там точно не меньше пол часа. На этот раз перед последним моим коммитом зависания не было.

**Comment by dapi** [comment]
Проверка - rails c и rails s запускаются

Установить
- [x] geo
- [x] zsh
- [x] oh my zsh
- [x] базу в постгресе создаются и удалятся от пользователя vagrant

**Comment by dapi** [comment]
а зачем RAILS_ENV=development ? Оно и так development считается если не установлено

**Comment by dapi** [comment]
- [x] локаль не установлена, ругается все время

**Comment by dapi** [comment]
```
‘/home/vagrant/.oh-my-zsh/templates/zshrc.zsh-template’ -> ‘/home/vagrant/.zshrc’
Cloning into '/home/vagrant/.rbenv'...
warning: expected SRV RR, found RR type 1
Cloning into '/home/vagrant/.rbenv/plugins/ruby-build'...
warning: expected SRV RR, found RR type 1
/home/vagrant/.oh-my-zsh/oh-my-zsh.sh: line 26: syntax error near unexpected token `('
/home/vagrant/.oh-my-zsh/oh-my-zsh.sh: line 26: `for config_file ($ZSH/lib/*.zsh); do'
```

.zshrc явно выполняется не в zsh а в bash-е

**Comment by dkhabarov** [comment]
Нет. Никим образом zsh не выполняется в баше.
Локаль - поправлю.

**Comment by dapi** [comment]
уже сам поправил

**Comment by dkhabarov** [comment]
03da1f0082e4606f6edb6f405f74e99af8d2f641- временно, надеюсь.
